USE [master]
GO

/****** Object:  Database [PetStore]    Script Date: 23/10/2015 14:26:32 ******/
CREATE DATABASE [PetStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PetStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.EXPRESS\MSSQL\DATA\PetStore.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PetStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.EXPRESS\MSSQL\DATA\PetStore_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PetStore] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PetStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PetStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PetStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PetStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PetStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PetStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [PetStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PetStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PetStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PetStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PetStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PetStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PetStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PetStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PetStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PetStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PetStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PetStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PetStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PetStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PetStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PetStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PetStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PetStore] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PetStore] SET  MULTI_USER 
GO

ALTER DATABASE [PetStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PetStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PetStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PetStore] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PetStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PetStore] SET  READ_WRITE 
GO

